### ISSUE TITLE
Auto-complete list is case-sensitive

### ISSUE THREAD

**Issue by Asuza** [austincrft/sublime-gherkin-auto-complete-plus#21] opened 2016-01-19 20:46 UTC
Is the list supposed to be case-sensitive? If so, could there be a config option to have it be case-insensitive?

**Comment by austincrft** [comment] 2016-01-20 22:39
I made it case sensitive because the regex used to match these steps are case-sensitive. What would be the benefit of making them not case-sensitive?

**Comment by Asuza** [comment] 2016-01-21 18:49
The benefit would be that it behaves more like the rest of Sublime auto-completion, which allows you to type in any case while still showing you the options.

As-is, if I have a couple of options, like

```
When I pass "someMethod" the object
When I pass "someMethod" the date
```

If I were to type `When i` then nothing would show up at all.

When I type `coolvar` into Sublime, it's auto-completion is going to show me

```
coolvar
Coolvar
coolVAR
```

or whatever else is spelled the same way, then I can just hit <kbd>Tab</kbd> and it will correct what I typed to be the case of whatever I chose in the list.

**Comment by austincrft** [comment] 2016-01-21 20:02
I agree with your points. The problem is with the way Sublime Text handles <kbd>space</kbd> in regard to auto-complete. Using a hack, I managed to make <kbd>space</kbd> close the auto-complete suggestion instead of committing it (which was more disruptive). When giving a suggestion on a new word, I'm displaying the entire line, but the part that gets committed is only the words that aren't present on the line yet.

As an example, let's say you have the following step:

``` gherkin
Given I have this example step
```

If you type

``` gherkin
Given I have t
```

there would actually be three different times the auto-complete would pop up, each suggestion not containing the previous words that have been typed.

The reason I'm explaining this is because if you typed

``` gherkin
Given i have t
```

The uncapitalized `I` wouldn't be corrected by pressing <kbd>tab</kbd>.

**Comment by Asuza** [comment] 2016-01-22 18:31
Okay, that makes a lot of sense. I think if #23 becomes a feature, then this issue is less of a problem.

**Comment by austincrft** [comment] 2016-01-22 18:34
Yeah, I agree. I'm closing this as wontfix.

**Closed as completed by austincrft** 2016-01-22 18:34 UTC
Labels: question, wontfix
